name: face_swapper
description: face swapper application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  google_fonts: ^6.1.0
  permission_handler: ^11.0.1
  image_gallery_saver: ^2.0.3
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/github.png
    - assets/google.png
    - assets/oxogames.png
    - assets/bald_man.PNG
    - assets/man_with_hair.PNG
    - assets/facebook.png
    - assets/linkedin.png
    - assets/instagram.png
    - assets/exemplary_man.png

